### ISSUE TITLE
Set on/off  not just toggle?

### ISSUE THREAD

**Issue by HeneryH** [sparkfunX/Qwiic_Quad_Relay#5]
I only see commands in the sample code to toggle individual relays.

I need to set a relay to ON.  Not just toggle it.

What is the command for setting relay x to ON or OFF?

**Comment by edspark** [comment]
Hello Henry!

Currently there is only the option to toggle the individual relays. I've been trying to imagine what situation a hard **on** command would be better than going from on->off->on etc. Do you mind sharing why you might need to do that? 

As a possible solution to your problem, you could use the command to get the status of the relay before you decide to turn it on or off. For example: "check if relay is on" --> if **off**, toggle relay otherwise leave it **on**.

**Comment by HeneryH** [comment]
I have a pi based home controller that communicates with a variety of arduino based wireless nodes.

I just created a node type for the Quad Relay Controller that allows me to set and check any of the relays.

On that controller are buttons to turn any relays on or off.   The functions I am writing take a relay index and a command (on/off).

I suppose that I just need to track its current state and if the requested state isn't the same as the current state then toggle.

**Comment by edspark** [comment]
Ah ok, yes yes. I think requesting the state of the relay is the way to go in your case, I believe the command is 0x05 for relay one, 0x06 for relay two, etc etc. Happy hacking!
